import { StyleSheet } from 'react-native';

export const theme = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: '#000',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 24,
    paddingTop: 24,
    width: '100%',
  },
  scrollContainer: {
    alignItems: 'center',
    backgroundColor: '#000',
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 24,
    paddingTop: 24,
    width: '100%',
  },
  header: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    paddingBottom: 24,
    paddingTop: 24,
    textAlign: 'center',
  },
  text: {
    color: '#f0ece1',
    fontSize: 14,
    fontWeight: 'bold',
    paddingBottom: 16,
    paddingTop: 16,
  },
  layout: {
    backgroundColor: '#000',
    flex: 1,
    width: '100%',
  },
  homeScreenImage: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 4,
    elevation: 3,
    justifyContent: 'center',
    marginBottom: 16,
    paddingHorizontal: 36,
    paddingVertical: 12,
    zIndex: 3,
  },
  buttonPressed: {
    alignItems: 'center',
    backgroundColor: '#5234eb',
    borderRadius: 4,
    elevation: 3,
    justifyContent: 'center',
    marginBottom: 16,
    paddingHorizontal: 36,
    paddingVertical: 12,
    zIndex: 3,
  },
  buttonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    lineHeight: 21,
  },
  link: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 2,
    elevation: 3,
    justifyContent: 'center',
    marginBottom: 16,
    width: 300,
    zIndex: 3,
  },
  linkPressed: {
    alignItems: 'center',
    backgroundColor: '#5234eb',
    borderRadius: 2,
    elevation: 3,
    justifyContent: 'center',
    marginBottom: 16,
    width: 300,
    zIndex: 3,
  },
  linkText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    lineHeight: 21,
  },
  keyText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  valueText: {
    color: '#fff',
    fontSize: 16,
  },
  warningText: {
    color: '#f24235',
    fontSize: 16,
    fontWeight: 'bold',
  },
  successText: {
    color: '#3cbd49',
    fontSize: 16,
    fontWeight: 'bold',
  },
  infoContainer: {
    alignItems: 'center',
    paddingBottom: 16,
  },
  underlinedLink: {
    color: '#fff',
    textDecorationLine: 'underline',
  },
  hyperLink: {
    color: 'blue',
    textAlign: 'left',
  }
});
